import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Raleway } from "next/font/google";
import { Toaster } from "react-hot-toast";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./styles/globals.css";
import { AudioPlayerProvider, useAudioPlayer } from "@/context/AudioContext";
import GlobalAudioPlayer from "@/context/GlobalAudioPlayer";

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${raleway.variable} antialiased`}>
        <NextIntlClientProvider messages={messages} timeZone="Asia/Tashkent">
          <AudioPlayerProvider>
            <Navbar />
            {children}
            <Footer />
            <Toaster position="top-center" reverseOrder={false} />
            <GlobalAudioPlayer />
          </AudioPlayerProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
